name: meal_roulette
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  go_router: ^6.0.1
  graphql: ^5.1.2
  graphql_flutter: ^5.1.1
  graphql_codegen: ^0.12.0-beta.6
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.3
  flutter_layout_grid: ^2.0.1
  google_fonts: ^3.0.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  built_value_generator: ^8.4.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mockito: ^5.3.2

dependency_overrides:
  analyzer: ^5.2.0

flutter:
  uses-material-design: true
